# Generated by Django 2.2.25 on 2022-05-24 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('PC', 'PC - Run windows '), ('Mac', ' MAc - Run MacOS '), ('Serveur', 'Serveur - Simple Server to deploy virtual machines'), ('Switch', 'Switch - To maintains and connect servers')], default='PC', max_length=32),
        ),
        migrations.AddField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 24, 8, 55, 32, 70099)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='nom',
            field=models.CharField(max_length=6),
        ),
    ]
