# Generated by Django 2.2.25 on 2022-06-11 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0017_auto_20220611_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 21, 29, 22, 129649)),
        ),
    ]
