# Generated by Django 2.2.25 on 2022-06-11 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0024_auto_20220611_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 22, 24, 36, 945329)),
        ),
    ]
