# Generated by Django 2.2.25 on 2022-06-12 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0037_auto_20220612_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 12, 16, 2, 15, 501963)),
        ),
    ]
