# Generated by Django 2.2.25 on 2022-06-13 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0038_auto_20220612_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 10, 28, 42, 133059)),
        ),
    ]
