# Generated by Django 2.2.25 on 2022-06-13 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0040_auto_20220613_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='date_recrutement',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 14, 3, 28, 106916)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 14, 3, 28, 106519)),
        ),
    ]
