# Generated by Django 2.2.25 on 2022-06-13 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0041_auto_20220613_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='date_recrutement',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 14, 5, 25, 170076)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 14, 5, 25, 169658)),
        ),
    ]
